### ISSUE TITLE
Won't compile with xserver ubuntu 16.04 (xorg 7.7)

### ISSUE THREAD

**Issue by RaphRi** [rkrell/xf86-video-sisimedia#2]
Hi ! 
I tried to compile this with xerserver from 16.04 to have better support wiht many old Fujitsu we have in our school.
it stops at this  : sis_driver.c:8770:5: error: too few arguments to function ‘pScreen->BlockHandle ’

I suppose a patch is needed to correspond to xenial's xserver release ?

For now I'm stuck with ubuntu 12.04. Thank you for help.

**Comment by RaphRi** [comment]
Forget about it. My SIS card is 661. it is in standard sis package
